spring.application.name=cms

server.port=8084
server.address=0.0.0.0

#app-management 
cms.app-management.url=http://10.195.55.55:9002/BIDC/AppManagement/doProcess

# Connection URL (Thin Driver)
spring.datasource.url=jdbc:oracle:thin:@//10.195.55.48:1521/TESTAPPDB
spring.datasource.username=internaldb
spring.datasource.password=internaldb
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
cms.db.schema-name=INTERNALDB
cms.db.catalog-name = PKG_CAMDx

#file management
cms.file-management.app-code = CMS
cms.file-management.upload.url=http://10.195.6.52:8082/upload
cms.file-management.download.url=http://10.195.6.52:8082/download
cms.file-management.user=bidc
cms.file-management.password=BIDc@12313210825
